# Generated by Django 3.0.10 on 2020-10-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code',
            name='password',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
