# Generated by Django 3.0.10 on 2020-10-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_auto_20201010_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.IntegerField(default=100),
        ),
    ]
