# Generated by Django 3.0.10 on 2020-10-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_auto_20201010_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
    ]
