# Generated by Django 3.0.10 on 2020-10-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_auto_20201010_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='password',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
