# Generated by Django 3.0.10 on 2020-10-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0006_auto_20201010_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created_utc',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='code',
            name='last_updated_utc',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
