# Generated by Django 3.0.10 on 2020-10-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0008_auto_20201010_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
