# Generated by Django 3.0.10 on 2020-10-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0010_auto_20201017_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='file_extension',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
