# Generated by Django 3.0.10 on 2020-10-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0011_language_file_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='last_updated_utc',
        ),
    ]
